// <auto-generated />
using System;
using Asp.Net_Projeto10_VocabularioDiario.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asp.Net_Projeto10_VocabularioDiario.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260308184434_CriacaoInicial")]
    partial class CriacaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Asp.Net_Projeto10_VocabularioDiario.Models.Palavra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ingles")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Portugues")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Palavras");
                });

            modelBuilder.Entity("Asp.Net_Projeto10_VocabularioDiario.Models.RegistroResposta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Acertou")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataResposta")
                        .HasColumnType("datetime2");

                    b.Property<int>("PalavraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PalavraId");

                    b.ToTable("RegistroRespostas");
                });

            modelBuilder.Entity("Asp.Net_Projeto10_VocabularioDiario.Models.RegistroResposta", b =>
                {
                    b.HasOne("Asp.Net_Projeto10_VocabularioDiario.Models.Palavra", "Palavra")
                        .WithMany()
                        .HasForeignKey("PalavraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Palavra");
                });
#pragma warning restore 612, 618
        }
    }
}
